name: test uv-sync action

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.11,3.12,3.13]
    
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: change directory
        run: cd test
      - name: install dependencies
        uses: .
          with:
            python-version: ${{ matrix.python-version }}
      - name: run script
        run: uv run main.py